assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: GI01SUMO-RII11-02-PHSENE041
stream:
  method: telemetered
  name: phsen_abcdef_imodem_control
workflow_config:
  schedule: 0 0 * * *
